from pathlib import Path

APP = Path("streamlit_app.py")
ENGINE = Path("engine/projection_engine.py")
RUNNER = Path("automation/daily_projection_runner.py")
TEST = Path("tests/test_matchup_weather_integrity.py")

app = APP.read_text(encoding="utf-8")
old = 'proj=calculate_projection(log,game,25000,float(opponent_matchup["k_rate"]),len(opposing_batters)); kdf=ladder(proj,10)\nfeatures_for_hits=build_engine_features(log,game,float(opponent_matchup["k_rate"]),len(opposing_batters))\n'
new = 'proj=calculate_projection(log,game,25000,float(opponent_matchup["k_rate"]),0); kdf=ladder(proj,10)\nfeatures_for_hits=build_engine_features(log,game,float(opponent_matchup["k_rate"]),0)\n'
if old not in app:
    raise SystemExit("projection batter quality anchor not found")
APP.write_text(app.replace(old, new, 1), encoding="utf-8")

engine = ENGINE.read_text(encoding="utf-8")
old = '''        enriched=dict(features)\n        try:\n            caller=inspect.currentframe().f_back; game=caller.f_locals.get("game") if caller is not None else None\n            if game is not None:\n                matchup=_matchup_context_from_game(game)\n                enriched["opponent_k_pct"]=float(matchup.get("opponent_k_pct",LEAGUE_K_RATE))\n                enriched["matchup_source"]=matchup.get("source","league baseline"); enriched["matchup_pa"]=float(matchup.get("matchup_pa",0.0)); enriched["matchup_hitters"]=float(matchup.get("matchup_hitters",0.0)); enriched["pitcher_hand"]=matchup.get("pitcher_hand","")\n        except Exception:\n            enriched.setdefault("matchup_source","league baseline")\n        features=enriched\n'''
new = '''        # Feature construction owns matchup selection. Never inspect the caller and\n        # silently replace an explicit opponent K input: that can make the visible\n        # batter box disagree with the probability engine and harms reproducibility.\n        enriched=dict(features)\n        enriched.setdefault("opponent_k_pct", LEAGUE_K_RATE)\n        enriched.setdefault("matchup_source", "explicit feature input")\n        features=enriched\n'''
if old not in engine:
    raise SystemExit("projection engine caller override anchor not found")
engine = engine.replace(old, new, 1)
# inspect is no longer needed after removing caller-frame behavior.
engine = engine.replace('import inspect\n', '', 1)
ENGINE.write_text(engine, encoding="utf-8")

runner = RUNNER.read_text(encoding="utf-8")
old = '''        existing = str(row.get("weather_delay_risk", "") or "").upper()\n        if existing in {"NONE", "LOW", "ELEVATED", "HIGH"}:\n            continue\n        try:\n            key = (int(row["game_pk"]), int(row["pitcher_id"]))\n        except Exception:\n            continue\n        scheduled = lookup.get(key)\n        if not scheduled:\n            continue\n        fields = weather_snapshot_fields(int(scheduled.get("venue_id", 0) or 0), str(scheduled.get("game_time", "")))\n        frame.at[idx, "venue_id"] = int(scheduled.get("venue_id", 0) or 0)\n        for key_name, value in fields.items():\n            frame.at[idx, key_name] = value\n        updated += 1\n'''
new = '''        try:\n            key = (int(row["game_pk"]), int(row["pitcher_id"]))\n        except Exception:\n            continue\n        scheduled = lookup.get(key)\n        if not scheduled:\n            continue\n        fields = weather_snapshot_fields(int(scheduled.get("venue_id", 0) or 0), str(scheduled.get("game_time", "")))\n        changed = False\n        venue_id = int(scheduled.get("venue_id", 0) or 0)\n        old_venue = pd.to_numeric(pd.Series([row.get("venue_id")]), errors="coerce").iloc[0]\n        if pd.isna(old_venue) or int(old_venue) != venue_id:\n            frame.at[idx, "venue_id"] = venue_id\n            changed = True\n        for key_name, value in fields.items():\n            old_value = row.get(key_name)\n            if pd.isna(value):\n                same = pd.isna(old_value)\n            else:\n                same = str(old_value) == str(value)\n            if not same:\n                frame.at[idx, key_name] = value\n                changed = True\n        if changed:\n            updated += 1\n'''
if old not in runner:
    raise SystemExit("weather refresh anchor not found")
RUNNER.write_text(runner.replace(old, new, 1), encoding="utf-8")

TEST.write_text('''from pathlib import Path\n\nimport numpy as np\nimport pandas as pd\n\nfrom engine.projection_engine import ProjectionEngine\nimport automation.daily_projection_runner as runner\n\n\ndef _features(opponent_k):\n    return {\n        "pitcher_k_pct": .24,\n        "opponent_k_pct": opponent_k,\n        "expected_bf": 23,\n        "bf_sd": 2.5,\n        "historical_k_sd": 2.0,\n        "historical_games": 20,\n        "lineup_batters": 0,\n        "arsenal_sample_size": 0,\n        "weather_available": 0,\n        "umpire_available": 0,\n        "handedness_factor": 1.0,\n        "arsenal_factor": 1.0,\n        "park_factor": 1.0,\n        "umpire_factor": 1.0,\n        "weather_factor": 1.0,\n        "rest_factor": 1.0,\n    }\n\n\ndef test_projection_engine_preserves_explicit_matchup_input():\n    low = ProjectionEngine(seed=7).project(_features(.15), draws=2000)\n    high = ProjectionEngine(seed=7).project(_features(.35), draws=2000)\n    assert high.ensemble_mean > low.ensemble_mean\n\n\ndef test_active_roster_batter_box_does_not_claim_confirmed_lineup_quality():\n    text = Path("streamlit_app.py").read_text(encoding="utf-8")\n    assert 'calculate_projection(log,game,25000,float(opponent_matchup["k_rate"]),0)' in text\n    assert 'build_engine_features(log,game,float(opponent_matchup["k_rate"]),0)' in text\n\n\ndef test_pregame_weather_can_change_on_later_refresh(monkeypatch):\n    frame = pd.DataFrame([{\n        "game_pk": 1, "pitcher_id": 2, "game_time": "2099-08-12T23:00:00Z",\n        "venue_id": 10, "weather_delay_risk": "NONE", "weather_icon": "",\n        "weather_precip_probability": 5.0, "weather_precip_mm": 0.0, "weather_summary": "Clear",\n    }])\n    announced = [{"game_pk": 1, "pitcher_id": 2, "game_time": "2099-08-12T23:00:00Z", "venue_id": 10}]\n    monkeypatch.setattr(runner, "weather_snapshot_fields", lambda venue_id, game_time: {\n        "weather_delay_risk": "HIGH", "weather_icon": "⛈️",\n        "weather_precip_probability": 80.0, "weather_precip_mm": 3.0, "weather_summary": "High weather-delay risk",\n    })\n    updated = runner.attach_pregame_weather(frame, announced)\n    assert updated == 1\n    assert frame.loc[0, "weather_delay_risk"] == "HIGH"\n    assert frame.loc[0, "weather_icon"] == "⛈️"\n\n\ndef test_projection_engine_has_no_caller_frame_matchup_override():\n    text = Path("engine/projection_engine.py").read_text(encoding="utf-8")\n    assert "inspect.currentframe" not in text\n    assert "silently replace an explicit opponent K input" in text\n''', encoding="utf-8")
