[theme]
base = "dark"
primaryColor = "#E31937"
backgroundColor = "#050D1A"
secondaryBackgroundColor = "#0B1D36"
textColor = "#F7FBFF"
font = "sans serif"
headingFont = "sans serif"
baseRadius = "large"
borderColor = "#294A6D"
showWidgetBorder = true
dataframeHeaderBackgroundColor = "#0E2748"

[client]
showSidebarNavigation = false

[server]
headless = true
